export const ALL_BLOG_REQUEST = "ALL_BLOG_REQUEST";
export const ALL_BLOG_SUCCESS = "ALL_BLOG_SUCCESS";
export const ALL_BLOG_FAIL = "ALL_BLOG_FAIL";

export const BLOG_DETAILS_REQUEST = "BLOG_DETAILS_REQUEST";
export const BLOG_DETAILS_SUCCESS = "BLOG_DETAILS_SUCCESS";
export const BLOG_DETAILS_FAIL = "BLOG_DETAILS_FAIL";

export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL";
export const CREATE_BLOG_RESET = "CREATE_BLOG_RESET";

export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL";
export const UPDATE_BLOG_RESET = "UPDATE_BLOG_RESET";

export const USER_BLOGS_REQUEST = "USER_BLOGS_REQUEST";
export const USER_BLOGS_SUCCESS = "USER_BLOGS_SUCCESS";
export const USER_BLOGS_FAIL = "USER_BLOGS_FAIL";

export const COMMENT_REQUEST = "COMMENT_REQUEST";
export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAIL = "COMMENT_FAIL";
export const COMMENT_RESET = "COMMENT_RESET";

export const COMMENT_DELETE_REQUEST = "COMMENT_DELETE_REQUEST";
export const COMMENT_DELETE_SUCCESS = "COMMENT_DELETE_SUCCESS";
export const COMMENT_DELETE_FAIL = "COMMENT_DELETE_FAIL";
export const COMMENT_DELETE_RESET = "COMMENT_DELETE_RESET";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

export const GET_A_CATEGORY_REQUEST = "GET_A_CATEGORY_REQUEST";
export const GET_A_CATEGORY_SUCCESS = "GET_A_CATEGORY_SUCCESS";
export const GET_A_CATEGORY_FAIL = "GET_A_CATEGORY_FAIL";

export const BLOG_DELETE_REQUEST = "BLOG_DELETE_REQUEST";
export const BLOG_DELETE_SUCCESS = "BLOG_DELETE_SUCCESS";
export const BLOG_DELETE_FAIL = "BLOG_DELETE_FAIL";
export const BLOG_DELETE_RESET = "BLOG_DELETE_RESET";

export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_FAIL = "UPDATE_STATUS_FAIL";
export const UPDATE_STATUS_RESET = "UPDATE_STATUS_RESET";

export const GET_SAVED_REQUEST = "GET_SAVED_REQUEST";
export const GET_SAVED_SUCCESS = "GET_SAVED_SUCCESS";
export const GET_SAVED_FAIL = "GET_SAVED_FAIL";

export const IS_SAVED_REQUEST = "IS_SAVED_REQUEST";
export const IS_SAVED_SUCCESS = "IS_SAVED_SUCCESS";
export const IS_SAVED_FAIL = "IS_SAVED_FAIL";

export const SAVE_BLOG_REQUEST = "SAVE_BLOG_REQUEST";
export const SAVE_BLOG_SUCCESS = "SAVE_BLOG_SUCCESS";
export const SAVE_BLOG_FAIL = "SAVE_BLOG_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
